blog/articles/views.py
import requests
from flask import Blueprint, render_template, request, current_app, redirect, url_for
from sqlalchemy.exc import IntegrityError

from blog.models import Article, User, Tag
from blog.models.database import db
from flask_login import login_required, current_user
from blog.forms import CreateArticleForm

host = "127.0.0.1"
port = "5000"
article = Blueprint('articles', __name__, url_prefix="/articles", static_folder="../static")


@article.route('/')
@login_required
def articles_list():
    # response = requests.get(f"http://{host}:{port}/api/articles/event_get_count/").json()
    # try:
    #     count = response['count']
    # except KeyError:
    #     count = 0
    articles = Article.query.all()
    return render_template("articles/list.html", articles=articles, user=current_user)


@article.route("<int:id>")
@login_required
def get_article(id: int):
    article = Article.query.filter_by(id=id).first()
    user = User.query.filter_by(id=article.author).first()
    return render_template("articles/details.html", article=article, user=user)


@article.route("/create/", methods=['POST', 'GET'], endpoint='create')
@login_required
def create_article():
    error = None
    form = CreateArticleForm(request.form)
    form.tags.choices = [(tag.id, tag.name) for tag in Tag.query.order_by("name")]
    if request.method == 'POST' and form.validate_on_submit():
        article = Article(title=form.title.data.strip(), text=form.text.data, author=current_user.id)
        if form.tags.data:
            selected_tags = Tag.query.filter(Tag.id.in_(form.tags.data))
            for tag in selected_tags:
                article.tags.append(tag)

        db.session.add(article)
        try:
            db.session.commit()
        except IntegrityError:
            current_app.logger.exception("Could not create a new article!")
            error = "Could not create article!"
        else:
            return redirect(url_for("articles.get_article", id=article.id))
    return render_template("articles/create.html", form=form, error=error)

blog/user/views.py
import requests
from flask import Blueprint, render_template, redirect
from werkzeug.exceptions import NotFound
from blog.models import User, Article

user = Blueprint('users', __name__, url_prefix="/users", static_folder="../static")
host = "127.0.0.1"
port = "5000"

@user.route('/')
def user_list():
    users = User.query.all()
    return render_template('users/list.html', users=users)


@user.route('/<int:pk>')
def get_user(pk: int):
    try:
        user = User.query.filter_by(id=pk).one_or_none()
        articles = Article.query.filter_by(author=user.id)
        # response = requests.get(f"https://flask-gb-cvrk.onrender.com/api/users/{pk}/event_get_article_count/").json()
        # try:
        #     count = response['count']
        # except KeyError:
        #     count = 0
    except KeyError:
        return redirect("/users/")
    return render_template('users/details.html', user=user, articles=articles)

blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block title %}Blog -{% endblock %}
    </title>
    {% block css %}
    <link href="{{url_for('static',filename='css/bootstrap.min.css')}}" rel="stylesheet">
    {% endblock %}
</head>

<body>
{% include 'navbar.html'%}
<div class="container">
    {% block body %} {% endblock %}
</div>

{% block js %}
<script src="{{url_for('static',filename='js/bootstrap.bundle.min.js')}}"></script>
{% endblock %}
</body>
</html>

blog/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Blog</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{{url_for('users.user_list')}}">Авторы</a>
                </li>
                <li class="nav-item">

                    <div class="row row-cols-auto">
                        <div class="col">
                            <a class="nav-link active" aria-current="page"
                               href="{{url_for('articles.articles_list')}}">Статьи</a>
                        </div>
                        <div class="col">
                            {% if current_user.is_authenticated %}

                            <a class="btn btn-primary" aria-current="page" href="{{url_for('articles.create')}}">Создать
                                статью</a>

                            {% endif %}
                        </div>
                    </div>
                </li>

                {% if current_user.is_authenticated %}
                <li class="nav-item">
                    <a class="btn btn-dark" aria-current="page" href="{{url_for('auth.logout')}}">Выйти</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>