blog/forms/article.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, validators, TextAreaField,SelectMultipleField


class CreateArticleForm(FlaskForm):
    title = StringField('Название статьи', [validators.DataRequired()])
    text = TextAreaField('Текст статьи', [validators.DataRequired()])
    tags = SelectMultipleField("Tags", coerce=int)
    submit = SubmitField("Сохранить")

blog/articles/views.py
import requests
from flask import Blueprint, render_template, request, current_app, redirect, url_for
from sqlalchemy.exc import IntegrityError

from blog.models import Article, User, Tag
from blog.models.database import db
from flask_login import login_required, current_user
from blog.forms import CreateArticleForm

host = "127.0.0.1"
port = "5000"
article = Blueprint('articles', __name__, url_prefix="/articles", static_folder="../static")


@article.route('/')
@login_required
def articles_list():
    # response = requests.get(f"http://{host}:{port}/api/articles/event_get_count/").json()
    # try:
    #     count = response['count']
    # except KeyError:
    #     count = 0
    articles = Article.query.all()
    return render_template("articles/list.html", articles=articles, user=current_user)


@article.route("<int:id>")
@login_required
def get_article(id: int):
    article = Article.query.filter_by(id=id).first()
    user = User.query.filter_by(id=article.author).first()
    return render_template("articles/details.html", article=article, user=user)


@article.route("/create/", methods=['POST', 'GET'], endpoint='create')
@login_required
def create_article():
    error = None
    form = CreateArticleForm(request.form)
    form.tags.choices = [(tag.id, tag.name) for tag in Tag.query.order_by("name")]
    if request.method == 'POST' and form.validate_on_submit():
        article = Article(title=form.title.data.strip(), text=form.text.data, author=current_user.id)
        if form.tags.data:
            selected_tags = Tag.query.filter(Tag.id.in_(form.tags.data))
            for tag in selected_tags:
                article.tags.append(tag)

        db.session.add(article)
        try:
            db.session.commit()
        except IntegrityError:
            current_app.logger.exception("Could not create a new article!")
            error = "Could not create article!"
        else:
            return redirect(url_for("articles.get_article", id=article.id))
    return render_template("articles/create.html", form=form, error=error)

blog/user/views.py
import requests
from flask import Blueprint, render_template, redirect
from werkzeug.exceptions import NotFound
from blog.models import User, Article

user = Blueprint('users', __name__, url_prefix="/users", static_folder="../static")
host = "127.0.0.1"
port = "5000"

@user.route('/')
def user_list():
    users = User.query.all()
    return render_template('users/list.html', users=users)


@user.route('/<int:pk>')
def get_user(pk: int):
    try:
        user = User.query.filter_by(id=pk).one_or_none()
        articles = Article.query.filter_by(author=user.id)
        # response = requests.get(f"https://flask-gb-cvrk.onrender.com/api/users/{pk}/event_get_article_count/").json()
        # try:
        #     count = response['count']
        # except KeyError:
        #     count = 0
    except KeyError:
        return redirect("/users/")
    return render_template('users/details.html', user=user, articles=articles)

blog/templates/articles/create.html
{% extends 'base.html'%}
{% from 'macro/formhelpers.html' import render_field %}
{% block title %}
{{ super() }} Создание статьи
{% endblock %}

{% block body %}
 {% if error %}
    <div class="alert alert-danger" role="alert">
        {{error}}
    </div>
    {% endif %}
<form method="post">
{{form.csrf_token()}}
    {% for field in ['title','text','tags']%}
    {{render_field(form[field])}}
    {% endfor%}
    <div>
        {{form.submit(class='btn btn-primary')}}
    </div>
</form>
{% endblock %}

blog/templates/articles/details.html
{% extends 'base.html'%}
{% block title %}
{{ super() }}
Article details

{% endblock %}
{% block body %}
<div class="row">
    <div class="col">
        <h1>Название: {{ article.title }}</h1>
        <h4>Дата выпуска: {{ article.date }}</h4>
        <h5>Текст: </h5>
        <p>{{article.text}}</p>
        {% if article.tags|length > 0 %}
        <h5>Теги: </h5>
        <ul>
            {% for tag in article.tags %}
            <li>{{ tag.name }}</li>
            {% endfor %}
        </ul>
        {% endif %}

        <a href="{{url_for('users.get_user',pk=article.author)}}" class="btn btn-primary">Автор: {{user.first_name}} {{
            user.last_name if user.last_name != None else ''}}</a>
    </div>
</div>
<h1>{{ user_name }}</h1>
{% endblock %}

blog/templates/articles/list.html
{% extends 'base.html' %}
{% block title %}
{{ super() }}
Articles
{% endblock %}
{% block body %}


<div class="row">
    <div class="col">
        <h1>Статьи </h1>
<!--        <p>Количество статей: {{count}}</p>-->
        {% for article in articles %}
        <div class="card w-75 mb-3">
            <div class="card-body">
                <h5 class="card-title">{{ article.title }}</h5>
                <p class="card-text">{{ article.text[:30] }}.....</p>
                <a href="{{url_for('articles.get_article',id=article.id)}}" class="btn btn-primary">Читать</a>
            </div>
        </div>
        {% endfor%}

    </div>
</div>
{% endblock %}